version: '3.8'

services:
  dev:
    container_name: nestjs_dev
    image: nestjs_dev:1.0.0
    build:
      context: .
      dockerfile: dockerfile
      target: dev
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    command: yarn start:dev
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - default
    restart: unless-stopped

  prod:
    container_name: nestjs_prod
    image: nestjs_prod:1.0.0
    build:
      context: .
      target: prod
      dockerfile: dockerfile
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    command: yarn start:prod
    ports:
      - 8080:8080
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - default
    restart: unless-stopped

  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresVolume:/var/lib/postgresql/data
      - ./logs:/logs
    networks:
      - default
    restart: always

  pgadmin:
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    image: dpage/pgadmin4
    ports:
      - 5050:80
    volumes:
      - pgadminVolume:/var/lib/pgadmin
    networks:
      - default
    restart: always

volumes:
  postgresVolume:
  pgadminVolume:

networks:
  default:
    driver: bridge
